const HttpError = require('../models/http-error');
const { v4: uuidv4 } = require('uuid');

const DUMMY_USERS = [
    {
        id: 'u1',
        name: 'Ugurcan Oruc',
        email: 'test@test.com',
        password: 'testers'
    }
]

const getUsers = (req, res, next) => {
    res.send(DUMMY_USERS)
};

const signup = (req, res, next) => {
    const { name, email, password} = req.body;

    const hasUser = DUMMY_USERS.find(user => user.email === email);

    if (hasUser) {
        throw new HttpError('Can not create user, email alread exists.', 422);
    }

    const createdUser = {
        id: uuidv4(),
        name,
        email,
        password
    };

    DUMMY_USERS.push(createdUser);

    res.status(201).send(createdUser);
};

const login = (req, res, next) => {
    const { email, password } = req.body;
    
    const identifiedUser = DUMMY_USERS.find(user => user.email === email);
    if (!identifiedUser || identifiedUser.password !== password) {
        throw new HttpError('Could not identify user, credentials seem to be wrong', 401);
    }

    res.send({ message: 'Logged in.'});
};

exports.getUsers = getUsers;
exports.signup = signup;
exports.login = login;